%teacher(T).
%class(Class,Grade).
%course(Name).
%qualified(Teacher,Course).
%curriculum(Grade,Course,Lessonsweek).
%formteacherOf(Teacher,Class).
%hasRelativeIn(Teacher,Class).
%assigned(Teacher,Class,Course).
%activity(ExtraActivity,Preperation).
%responsibleFor(Teacher,ExtraActivity).

%a2
%nur qualifizierte lehrer sollen die klasse auch unterrichten

teacher(lehrer1).
class(klasse1,1).
course(kurs1).
curriculum(1,kurs1,2).
formteacherOf(lehrer1,klasse1).
assigned(lehrer1,klasse1,kurs1).
activity(extra,1).
responsibleFor(lehrer1,extra).


%qualified(lehrer1,kurs1).
