%teacher(T).
%class(Class,Grade).
%course(Name).
%qualified(Teacher,Course).
%curriculum(Grade,Course,Lessonsweek).
%formteacherOf(Teacher,Class).
%hasRelativeIn(Teacher,Class).
%assigned(Teacher,Class,Course).
%activity(ExtraActivity,Preperation).
%responsibleFor(Teacher,ExtraActivity).

%i2
%classes nur in 1-4 grade und keine zwei verschiedenen grades fuer klasse

teacher(lehrer1).
class(klasse1,8).
course(kurs1).
qualified(lehrer1,kurs1).
curriculum(1,kurs1,2).
formteacherOf(lehrer1,klasse1).
assigned(lehrer1,klasse1,kurs1).
activity(extra,1).
responsibleFor(lehrer1,extra).

class(klasse2,1).
class(klasse2,2).
